apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongos
  template:
    metadata:
      labels:
        app: mongos
    spec:
      containers:
      - name: mongos
        image: mongo
        command:
          - "mongos"
          - "--configdb"
          - "cfgrs/config-server-0.config-server.default.svc.cluster.local:27201,config-server-1.config-server.default.svc.cluster.local:27201,config-server-2.config-server.default.svc.cluster.local:27201"
          - "--bind_ip"
          - "0.0.0.0"
          - "--port"
          - "27100"
        ports:
        - containerPort: 27100
